### ISSUE TITLE
Default values disappear from field

### ISSUE THREAD

**Issue by batlanyard** [Ahmed-Ali/RealmObjectEditor#3] opened 2015-02-04 22:26 UTC
Great tool! Noticed that when you set a default value for a key, the "Default" checkbox is checked but the value "disappears" from the UI.

On export, the default values are defined in the entity though.

Nice work overall and very useful. Thanks!

![screen shot 2015-02-04 at 4 25 12 pm](https://cloud.githubusercontent.com/assets/1168446/6051070/83d37c1e-ac8a-11e4-9a9c-5525e252d32c.png)
![screen shot 2015-02-04 at 4 25 33 pm](https://cloud.githubusercontent.com/assets/1168446/6051073/890a46b8-ac8a-11e4-891b-199bf2f68594.png)

**Comment by Ahmed-Ali** [comment] 2015-02-04 22:45
Thanks for reporting it @batlanyard. Will publish the fix tomorrow night (23:00 GMT) max.

Hope you are enjoying it :)

**Comment by Ahmed-Ali** [comment] 2015-02-05 19:11
Strangely enough I have tried to reproduce it many times but I could not!

**Comment by batlanyard** [comment] 2015-02-12 20:13
I noticed it when editing a model I'd already created. Maybe it's the reopen to edit?

(edited to delete 2nd comment - my mistake)

**Comment by Ahmed-Ali** [comment] 2015-03-02 02:27
Hi @batlanyard, sorry for the late reply. I also tried to reproduce it using a saved document but could not reproduce.
If it is possible to list the steps which lead to the bug please do, maybe there is something I am missing.

**Comment by batlanyard** [comment] 2015-03-18 20:35
Sorry for the delay as well! Here's a short screen capture of what I'm seeing. The default values are not shown once set (in the space next to the default checkbox):

https://db.tt/k4ecsbs6

**Comment by Ahmed-Ali** [comment] 2015-09-04 13:57
Hi @batlanyard,
You can try the latest version (0.0.3) it should be fixed now.

**Closed as completed by Ahmed-Ali** 2015-09-04 13:57 UTC
